### ISSUE TITLE
Battery % always wrong

### ISSUE THREAD

**Issue by reinisb** [dmitry-cherkas/esphome-danfoss-eco#23]
The reported battery % is always wrong. When I install brand new batteries, it shows 36% and then over days goes down to 25% and stays at that level. Any ideas?

<img width="1129" alt="Screenshot 2024-01-29 at 00 54 20" src="https://github.com/dmitry-cherkas/esphome-danfoss-eco/assets/6346595/a945d9c1-2927-41ec-ab98-c232f6b141a4">

**Comment by ckoca** [comment]
You are probably using rechargable NiMH batteries. Those have a nominal voltage of 1.2V compared to alkaline batteries with 1.5V. That's why you are seeing a much lower battery charge percentage even at full charge. The discharge curve of NiMH batteries is much less steep than Alkaline batteries though, so you should be able to use them for a long time at about 25% charge.

![nimh_vs_alkaline.gif](https://github.com/dmitry-cherkas/esphome-danfoss-eco/assets/32613747/f631c52d-6dc0-4038-9857-01bba10678f8)

[Image Source](http://www.stefanv.com/electronics/using_nimh.html)

**Comment by reinisb** [comment]
Ah, you are absolutely right, I did not think of NiMH causing this! Thanks a lot for the context.
